export const GET_ALL_POSTS_REQUEST = 'GET_ALL_POSTS_REQUEST'
export const GET_ALL_POSTS_SUCCEEDED = 'GET_ALL_POSTS_SUCCEEDED'
export const GET_ALL_POSTS_FAILED = 'GET_ALL_POSTS_FAILED'
export const SEARCH_REQUEST = 'SEARCH_REQUEST'
export const SEARCH_RESULT = 'SEARCH_RESULT'
export const SEARCH_RESULT_RESET = 'SEARCH_RESULT_RESET'
export const SET_FILTER = 'SET_FILTER'

export const filter = {
  NONE: 'NONE',
  BYDATE: 'BYDATE',
  BYVIEW: 'BYVIEW'
}
